# Generated by Django 6.0.1 on 2026-02-24 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prompt_service', '0006_prompt_lineage_metadata_json_prompt_origin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriftRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(db_index=True, default='global', max_length=64)),
                ('status', models.CharField(choices=[('running', 'running'), ('completed', 'completed'), ('failed', 'failed')], default='running', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('metrics_json', models.JSONField(default=dict)),
                ('ga_triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DriftSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('embedding_centroid_shift', 'embedding_centroid_shift'), ('qscore_degradation', 'qscore_degradation'), ('feedback_deterioration', 'feedback_deterioration')], max_length=64)),
                ('severity', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=16)),
                ('score', models.FloatField()),
                ('threshold', models.FloatField()),
                ('scope', models.CharField(db_index=True, default='global', max_length=64)),
                ('metadata_json', models.JSONField(default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('drift_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='drift_detection_service.driftrun')),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drift_signals', to='prompt_service.prompt')),
            ],
            options={
                'ordering': ['-detected_at', '-id'],
            },
        ),
    ]
