# Generated by Django 6.0.1 on 2026-02-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift_detection_service', '0001_initial'),
        ('prompt_service', '0007_prompt_owner_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driftrun',
            name='subject_user_id',
            field=models.CharField(db_index=True, default='legacy-global', max_length=128),
        ),
        migrations.AddField(
            model_name='driftsignal',
            name='subject_user_id',
            field=models.CharField(db_index=True, default='legacy-global', max_length=128),
        ),
        migrations.AddIndex(
            model_name='driftrun',
            index=models.Index(fields=['subject_user_id', 'started_at'], name='drift_detec_subject_0e5407_idx'),
        ),
        migrations.AddIndex(
            model_name='driftrun',
            index=models.Index(fields=['subject_user_id', 'ga_triggered', 'started_at'], name='drift_detec_subject_5894b1_idx'),
        ),
        migrations.AddIndex(
            model_name='driftsignal',
            index=models.Index(fields=['subject_user_id', 'detected_at'], name='drift_detec_subject_17bda8_idx'),
        ),
    ]
