# Generated by Django 6.0.1 on 2026-02-24 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history_service', '0003_turn_prompt_fk'),
        ('ratings_service', '0002_seed_qscore_v0'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('failed', 'failed'), ('done', 'done')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.IntegerField(default=0)),
                ('payload_json', models.JSONField(default=dict)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embedding_sync_jobs', to='ratings_service.turnfeedback')),
                ('turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embedding_sync_jobs', to='history_service.turn')),
            ],
            options={
                'ordering': ['status', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TurnEmbeddingIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('question', 'question'), ('assistant', 'assistant'), ('feedback', 'feedback')], max_length=16)),
                ('vector_id', models.CharField(max_length=128, unique=True)),
                ('embedding_model_version', models.CharField(max_length=64)),
                ('embedding_json', models.JSONField(default=list)),
                ('metadata_json', models.JSONField(default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embedding_documents', to='ratings_service.turnfeedback')),
                ('turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embedding_documents', to='history_service.turn')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
