# Generated by Django 6.0.1 on 2026-01-07 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history_service', '0002_update_history_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=32)),
                ('config_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TurnFeedback',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('user_id', models.CharField(db_index=True, max_length=128)),
                ('rating_correctness', models.IntegerField()),
                ('rating_helpfulness', models.IntegerField()),
                ('rating_clarity', models.IntegerField()),
                ('free_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'turn',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='feedback_entries',
                        to='history_service.turn',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TurnEvaluation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('q_total', models.FloatField()),
                ('q_correctness', models.FloatField()),
                ('q_helpfulness', models.FloatField()),
                ('q_pedagogy', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'evaluator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='turn_evaluations',
                        to='ratings_service.evaluator',
                    ),
                ),
                (
                    'turn',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='evaluations',
                        to='history_service.turn',
                    ),
                ),
            ],
        ),
    ]
