# Generated by Django 6.0.1 on 2026-03-10

from django.db import migrations, models


def seed_qscore_v2(apps, schema_editor):
    Evaluator = apps.get_model('ratings_service', 'Evaluator')
    Evaluator.objects.filter(name='qscore_v0').delete()
    Evaluator.objects.update_or_create(
        name='qscore_v2',
        version='2.0.0',
        defaults={
            'config_json': {
                'weights': {
                    'w_progress': 0.4737,
                    'w_confusion_reduction': 0.2632,
                    'w_clarity': 0.1579,
                    'w_engagement': 0.1053,
                },
                'rating_scale': {'min': 1, 'max': 5},
            }
        },
    )


def unseed_qscore_v2(apps, schema_editor):
    Evaluator = apps.get_model('ratings_service', 'Evaluator')
    Evaluator.objects.filter(name='qscore_v2', version='2.0.0').delete()
    Evaluator.objects.get_or_create(
        name='qscore_v0',
        version='0.1.0',
        defaults={
            'config_json': {
                'weights': {'wc': 0.4, 'wh': 0.4, 'wp': 0.2},
                'rating_scale': {'min': 1, 'max': 5},
                'guardrail_tag': 'guardrails',
            }
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_service', '0002_seed_qscore_v0'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnevaluation',
            name='q_clarity',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnevaluation',
            name='q_confusion_reduction',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnevaluation',
            name='q_engagement',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnevaluation',
            name='q_progress',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnfeedback',
            name='rating_clarity_understanding',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnfeedback',
            name='rating_engagement_fit',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnfeedback',
            name='rating_perceived_progress',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='turnevaluation',
            name='q_correctness',
        ),
        migrations.RemoveField(
            model_name='turnevaluation',
            name='q_helpfulness',
        ),
        migrations.RemoveField(
            model_name='turnevaluation',
            name='q_pedagogy',
        ),
        migrations.RemoveField(
            model_name='turnfeedback',
            name='rating_clarity',
        ),
        migrations.RemoveField(
            model_name='turnfeedback',
            name='rating_correctness',
        ),
        migrations.RemoveField(
            model_name='turnfeedback',
            name='rating_helpfulness',
        ),
        migrations.RunPython(seed_qscore_v2, unseed_qscore_v2),
    ]
