# Generated by Django 6.0.1 on 2026-02-24 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drift_detection_service', '0001_initial'),
        ('prompt_service', '0006_prompt_lineage_metadata_json_prompt_origin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptEvolutionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(default='system', max_length=32)),
                ('status', models.CharField(choices=[('running', 'running'), ('completed', 'completed'), ('failed', 'failed')], default='running', max_length=16)),
                ('generated_count', models.IntegerField(default=0)),
                ('published_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('drift_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolution_runs', to='drift_detection_service.driftsignal')),
                ('parent_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_runs', to='prompt_service.prompt')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PromptVariantCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('mutation_operator', models.CharField(max_length=64)),
                ('score', models.FloatField(default=0.0)),
                ('passed_safety', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('generated', 'generated'), ('published', 'published'), ('rejected', 'rejected')], default='generated', max_length=16)),
                ('metadata_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evolution_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='ga_service.promptevolutionrun')),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_candidates', to='prompt_service.prompt')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
