# Generated by Django 6.0.1 on 2026-02-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ga_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptevolutionrun',
            name='subject_user_id',
            field=models.CharField(db_index=True, default='legacy-global', max_length=128),
        ),
    ]
