# Generated by Django 6.0.1 on 2026-01-07 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prompt',
            new_name='PromptVersion',
        ),
        migrations.AddField(
            model_name='promptversion',
            name='policy_tags_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='promptversion',
            name='parent_prompt',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='child_prompts',
                to='prompt_service.promptversion',
            ),
        ),
    ]
