# Generated by Django 6.0.1 on 2026-01-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_service', '0002_promptversion_fields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PromptVersion',
            new_name='Prompt',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='version',
        ),
        migrations.AlterModelOptions(
            name='prompt',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
