# Generated by Codex on 2026-02-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history_service', '0001_initial'),
        ('prompt_service', '0003_prompt_revert_and_drop_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationBanditState',
            fields=[
                ('conversation_id', models.UUIDField(primary_key=True, serialize=False)),
                ('ema_q', models.FloatField(default=0.5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromptDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.UUIDField(db_index=True)),
                ('turn_number', models.IntegerField()),
                ('ema_q_at_decision', models.FloatField()),
                ('context_vector', models.JSONField(default=list)),
                ('sampled_score', models.FloatField()),
                ('model_version', models.CharField(max_length=32)),
                ('context_version', models.CharField(max_length=32)),
                ('chosen_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.FloatField(blank=True, null=True)),
                ('reward_computed_at', models.DateTimeField(blank=True, null=True)),
                ('reward_version', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'ordering': ['-chosen_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BanditArmState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d', models.IntegerField(default=5)),
                ('gamma', models.FloatField(default=0.997)),
                ('lambda_prior', models.FloatField(default=1.0)),
                ('alpha', models.FloatField(default=1.0)),
                ('A_inv', models.JSONField(default=list)),
                ('b', models.JSONField(default=list)),
                ('effective_n', models.FloatField(default=0.0)),
                ('model_version', models.CharField(max_length=32)),
                ('context_version', models.CharField(max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bandit_state', to='prompt_service.prompt')),
            ],
        ),
        migrations.AddField(
            model_name='promptdecision',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_decisions', to='prompt_service.prompt'),
        ),
        migrations.AddField(
            model_name='promptdecision',
            name='turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_decisions', to='history_service.turn'),
        ),
    ]
