# Generated by Codex on 2026-02-22

import django.db.models.deletion
from django.db import migrations, models


def hard_reset_bandit_data(apps, schema_editor):
    PromptDecision = apps.get_model('prompt_service', 'PromptDecision')
    BanditArmState = apps.get_model('prompt_service', 'BanditArmState')
    ConversationBanditState = apps.get_model('prompt_service', 'ConversationBanditState')

    PromptDecision.objects.all().delete()
    BanditArmState.objects.all().delete()
    ConversationBanditState.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_service', '0004_mab_bandit_models'),
    ]

    operations = [
        migrations.RunPython(hard_reset_bandit_data, migrations.RunPython.noop),
        migrations.AddField(
            model_name='promptdecision',
            name='learner_id',
            field=models.CharField(db_index=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='promptdecision',
            old_name='sampled_score',
            new_name='sampled_theta',
        ),
        migrations.RemoveField(
            model_name='promptdecision',
            name='context_version',
        ),
        migrations.RemoveField(
            model_name='promptdecision',
            name='context_vector',
        ),
        migrations.RemoveField(
            model_name='promptdecision',
            name='ema_q_at_decision',
        ),
        migrations.CreateModel(
            name='BanditUserArmState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(db_index=True, max_length=128)),
                ('mu0', models.FloatField(default=0.5)),
                ('lambda0', models.FloatField(default=4.0)),
                ('eta', models.FloatField(default=0.0)),
                ('nu', models.FloatField(default=0.0)),
                ('sigma_r', models.FloatField(default=0.2)),
                ('alpha', models.FloatField(default=1.0)),
                ('gamma', models.FloatField(default=0.998)),
                ('effective_n', models.FloatField(default=0.0)),
                ('model_version', models.CharField(max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'prompt',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user_bandit_states',
                        to='prompt_service.prompt',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='bandituserarmstate',
            constraint=models.UniqueConstraint(
                fields=('learner_id', 'prompt'),
                name='unique_learner_prompt_bandit_state',
            ),
        ),
        migrations.DeleteModel(
            name='BanditArmState',
        ),
        migrations.DeleteModel(
            name='ConversationBanditState',
        ),
    ]
