# Generated by Django 6.0.1 on 2026-02-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_service', '0005_per_user_ts_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='lineage_metadata_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='prompt',
            name='origin',
            field=models.CharField(choices=[('manual', 'manual'), ('ga', 'ga')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='prompt',
            name='rollout_pct',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='prompt',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('candidate', 'candidate'), ('retired', 'retired')], db_index=True, default='active', max_length=16),
        ),
    ]
