# Generated by Django 6.0.1 on 2026-02-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_service', '0006_prompt_lineage_metadata_json_prompt_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='owner_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['is_active', 'status', 'owner_user_id'], name='prompt_serv_is_acti_96bb11_idx'),
        ),
    ]
