"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!o@!+ku1so48k-c@21(&8-e)#!y8=y&z3&w!v-p0x=y%50mzga'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'apps.api',
    'apps.handler',
    'apps.llm_service',
    'apps.prompt_service',
    'apps.history_service',
    'apps.ratings_service',
    'apps.accounts',
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'app'
LOGOUT_REDIRECT_URL = 'login'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LLM_API_URL = os.getenv('LLM_API_URL', 'https://api.x.ai/v1/chat/completions')
LLM_API_KEY = os.getenv('LLM_API_KEY', '')
LLM_TIMEOUT_SECONDS = int(os.getenv('LLM_TIMEOUT_SECONDS', '15'))
LLM_DEFAULT_MODEL = os.getenv('LLM_DEFAULT_MODEL', 'grok-4-1-fast-non-reasoning')
LLM_DEFAULT_TEMPERATURE = float(os.getenv('LLM_DEFAULT_TEMPERATURE', '0.7'))
LLM_DEFAULT_MAX_TOKENS = int(os.getenv('LLM_DEFAULT_MAX_TOKENS', '512'))


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {'1', 'true', 'yes', 'on'}


OBSERVABILITY_MODE = _env_bool('OBSERVABILITY_MODE', False)
OBS_EVENTS_STRICT = _env_bool('OBS_EVENTS_STRICT', False)
OBS_REDIS_URL = os.getenv('OBS_REDIS_URL', 'redis://localhost:6379/0')
OBS_REDIS_STREAM_KEY = os.getenv('OBS_REDIS_STREAM_KEY', 'atl:state-events')
OBS_REDIS_MAXLEN = int(os.getenv('OBS_REDIS_MAXLEN', '2000'))
NINJA_PANEL_URL = os.getenv('NINJA_PANEL_URL', 'http://localhost:3001')

_baseline_prompt_id_raw = os.getenv('BASELINE_PROMPT_ID', '').strip()
BASELINE_PROMPT_ID = int(_baseline_prompt_id_raw) if _baseline_prompt_id_raw else None
