# Generated by Django 6.0.1 on 2026-01-07 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=64, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_index', models.IntegerField()),
                ('user_text', models.TextField()),
                ('assistant_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata_json', models.JSONField(default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='history_service.conversation')),
            ],
            options={
                'ordering': ['turn_index'],
                'unique_together': {('conversation', 'turn_index')},
            },
        ),
    ]
