# Generated by Django 6.0.1 on 2026-01-07 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_service', '0003_prompt_revert_and_drop_version'),
        ('history_service', '0002_update_history_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turn',
            old_name='prompt_version',
            new_name='prompt',
        ),
        migrations.AlterField(
            model_name='turn',
            name='prompt',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='turns',
                to='prompt_service.prompt',
            ),
        ),
    ]
